/* Parcours 4 — Everyday Life (A1-A2) : courses, restaurant, hôtel.
   Format : voir parcours/README.md */
(window.EXPATIA = window.EXPATIA || {}).everyday = [
  {id:'day-shop',emoji:'🛒',kind:'mixed',title:'Au supermarché',desc:'Trouver un produit, les promotions, payer, rendre un article.',
    words:[
      ['Supermarket','Supermarché','سوبرماركت','🏬','SOU-peu-mâ-kit'],
      ['Trolley','Chariot','عربة التسوق','🛒','TRO-li'],
      ['Checkout','Caisse','الكاشير','🧾','TCHÈK-aout'],
      ['Bag','Sac','كيس','🛍️','BAG'],
      ['Where can I find the rice?','Où puis-je trouver le riz ?','أين أجد الأرز؟','🍚','OUÈ kann aï FAÏND ðeu RAÏS'],
      ['Is this on offer?','Est-ce en promotion ?','هل هذا عليه عرض؟','🏷️','iz ðis onn O-feu'],
      ['Do you have a smaller size?','Avez-vous un format plus petit ?','هل لديك حجم أصغر؟','📏','dou you HAV eu SMO-leu SAÏZ'],
      ['I’d like to return this.','Je voudrais rendre cet article.','أريد إرجاع هذا.','↩️','aïd LAÏK tou ri-TEUN ðis']
    ],
    dialogue:[
      {scene:'Dans les rayons'},
      {who:'Staff',en:'Hi, are you looking for something?',fr:'Bonjour, vous cherchez quelque chose ?',ar:'مرحبًا، هل تبحث عن شيء؟',ph:'HAÏ, â you LOU-kinng fô SAM-þinng'},
      {me:true,choices:['Yes, where can I find the rice?','Yes, where is the baggage claim?','Yes, I’m looking for an apartment.'],fr:'Oui, où puis-je trouver le riz ?',ar:'نعم، أين أجد الأرز؟',ph:'YÈS, OUÈ kann aï FAÏND ðeu RAÏS'},
      {who:'Staff',en:'Aisle five, next to the pasta.',fr:'Allée cinq, à côté des pâtes.',ar:'الممر خمسة، بجانب المعكرونة.',ph:'AÏL FAÏV, NÈKST tou ðeu PAS-ta'},
      {me:true,choices:['Thank you. Is this on offer?','Thank you. Is this your first visit?','Thank you. Is the rent negotiable?'],fr:'Merci. Est-ce en promotion ?',ar:'شكرًا. هل هذا عليه عرض؟',ph:'þANK you. iz ðis onn O-feu'},
      {who:'Staff',en:'Yes, buy one, get one free.',fr:'Oui, un acheté, un offert.',ar:'نعم، اشترِ واحدًا واحصل على الثاني مجانًا.',ph:'YÈS, BAÏ OUANN, guèt OUANN FRI'},
      {scene:'À la caisse'},
      {who:'Cashier',en:'Do you need a bag?',fr:'Vous avez besoin d’un sac ?',ar:'هل تحتاج إلى كيس؟',ph:'dou you NID eu BAG'},
      {me:true,choices:['Yes, please. Can I pay by card?','Yes, please. Fill it up.','Yes, please. One bedroom.'],fr:'Oui, s’il vous plaît. Puis-je payer par carte ?',ar:'نعم من فضلك. هل يمكنني الدفع بالبطاقة؟',ph:'YÈS, PLIZ. kann aï PÉÏ baï KÂD'},
      {who:'Cashier',en:'Sure. That’s sixty-two dirhams.',fr:'Bien sûr. Ça fait soixante-deux dirhams.',ar:'بالتأكيد. المبلغ اثنان وستون درهمًا.',ph:'CHÔ. ðats SIKS-ti-TOU DIR-hamz'},
      {me:true,choices:['Here you are. Can I have the receipt?','Here you are. Welcome to Dubai.','Here you are. Where to?'],fr:'Voilà. Puis-je avoir le ticket de caisse ?',ar:'تفضل. هل يمكنني الحصول على الإيصال؟',ph:'HIEU you Â. kann aï HAV ðeu ri-SIT'}
    ]},
  {id:'day-restaurant',emoji:'🍽️',kind:'phrases',title:'Au restaurant',desc:'Réserver, commander, signaler une allergie, payer.',
    words:[
      ['I’d like to book a table for two.','Je voudrais réserver une table pour deux.','أريد حجز طاولة لشخصين.','📞','aïd LAÏK tou BOUK eu TÉÏ-beul fô TOU'],
      ['Can I see the menu, please?','Puis-je voir la carte, s’il vous plaît ?','هل يمكنني رؤية قائمة الطعام من فضلك؟','📋','kann aï SI ðeu MÈ-niou, PLIZ'],
      ['What do you recommend?','Que recommandez-vous ?','ماذا تنصح؟','⭐','OUOT dou you rè-keu-MÈND'],
      ['I’m allergic to nuts.','Je suis allergique aux fruits à coque.','لدي حساسية من المكسرات.','🥜','aïm eu-LEU-djik tou NATS'],
      ['Does it contain gluten?','Y a-t-il du gluten ?','هل يحتوي على الغلوتين؟','🌾','deuz it keun-TÉÏN GLOU-teun'],
      ['I’ll have the grilled chicken.','Je vais prendre le poulet grillé.','سآخذ الدجاج المشوي.','🍗','aïl HAV ðeu GRILD TCHI-kinn'],
      ['Could we have the bill, please?','Pourrions-nous avoir l’addition, s’il vous plaît ?','هل يمكننا الحصول على الفاتورة من فضلك؟','🧾','koud oui HAV ðeu BIL, PLIZ'],
      ['This is cold. Could you warm it up?','C’est froid. Pourriez-vous le réchauffer ?','هذا بارد. هل يمكنك تسخينه؟','🥶','ðis iz KOLD. koud you OUÔM it AP']
    ],
    dialogue:[
      {scene:'Au restaurant'},
      {who:'Waiter',en:'Good evening. Do you have a reservation?',fr:'Bonsoir. Avez-vous une réservation ?',ar:'مساء الخير. هل لديك حجز؟',ph:'goud IV-ninng. dou you HAV eu rè-zeu-VÉÏ-cheun'},
      {me:true,choices:['Yes, a table for two, under the name Karim.','Yes, a work visa for two weeks.','Yes, a one-bedroom apartment.'],fr:'Oui, une table pour deux, au nom de Karim.',ar:'نعم، طاولة لشخصين باسم كريم.',ph:'YÈS, eu TÉÏ-beul fô TOU, ANN-deu ðeu NÉÏM ka-RIM'},
      {who:'Waiter',en:'This way, please. Here is the menu.',fr:'Par ici, s’il vous plaît. Voici la carte.',ar:'من هنا من فضلك. تفضل قائمة الطعام.',ph:'ðis OUÉÏ, PLIZ. HIR iz ðeu MÈ-niou'},
      {me:true,choices:['Thank you. What do you recommend?','Thank you. What is the exchange rate?','Thank you. What time is the flight?'],fr:'Merci. Que recommandez-vous ?',ar:'شكرًا. ماذا تنصح؟',ph:'þANK you. OUOT dou you rè-keu-MÈND'},
      {who:'Waiter',en:'The grilled chicken is very popular.',fr:'Le poulet grillé a beaucoup de succès.',ar:'الدجاج المشوي مطلوب جدًا.',ph:'ðeu GRILD TCHI-kinn iz VÈ-ri PO-piou-leu'},
      {me:true,choices:['Does it contain nuts? I’m allergic.','Does it have a sea view?','Does it take thirty minutes by taxi?'],fr:'Y a-t-il des fruits à coque ? Je suis allergique.',ar:'هل يحتوي على مكسرات؟ لدي حساسية.',ph:'deuz it keun-TÉÏN NATS ? aïm eu-LEU-djik'},
      {who:'Waiter',en:'No, there are no nuts in it.',fr:'Non, il n’y a pas de fruits à coque.',ar:'لا، لا يحتوي على مكسرات.',ph:'NO, ðèr â NO NATS inn it'},
      {me:true,choices:['Great, I’ll have the grilled chicken.','Great, I’ll take the apartment.','Great, I’ll top up my Nol card.'],fr:'Parfait, je vais prendre le poulet grillé.',ar:'رائع، سآخذ الدجاج المشوي.',ph:'GRÉÏT, aïl HAV ðeu GRILD TCHI-kinn'},
      {scene:'À la fin du repas'},
      {who:'Waiter',en:'Would you like a dessert?',fr:'Voulez-vous un dessert ?',ar:'هل تريد حلوى؟',ph:'woud you LAÏK eu di-ZEUT'},
      {me:true,choices:['No, thank you. Could we have the bill, please?','No, thank you. Could you repeat the address?','No, thank you. Can I see the kitchen?'],fr:'Non merci. Pourrions-nous avoir l’addition, s’il vous plaît ?',ar:'لا شكرًا. هل يمكننا الحصول على الفاتورة من فضلك؟',ph:'NO, þANK you. koud oui HAV ðeu BIL, PLIZ'}
    ]},
  {id:'day-hotel',emoji:'🏨',kind:'phrases',title:'À l’hôtel',desc:'Arriver, poser vos questions, signaler un problème.',
    words:[
      ['I have a reservation.','J’ai une réservation.','لدي حجز.','📑','aï HAV eu rè-zeu-VÉÏ-cheun'],
      ['What time is check-out?','À quelle heure faut-il libérer la chambre ?','متى موعد تسجيل المغادرة؟','🕛','OUOT TAÏM iz TCHÈK-aout'],
      ['Is breakfast included?','Le petit-déjeuner est-il inclus ?','هل الإفطار مشمول؟','🥐','iz BRÈK-feust inn-KLOU-did'],
      ['Could I have a late check-out?','Pourrais-je libérer la chambre plus tard ?','هل يمكنني المغادرة في وقت متأخر؟','⏰','koud aï HAV eu LÉÏT TCHÈK-aout'],
      ['The Wi-Fi isn’t working in my room.','Le Wi-Fi ne marche pas dans ma chambre.','الواي فاي لا يعمل في غرفتي.','📶','ðeu OUAÏ-faï IZ-eunt WEU-kinng inn maï ROUM'],
      ['Could I have another room?','Pourrais-je avoir une autre chambre ?','هل يمكنني الحصول على غرفة أخرى؟','🔁','koud aï HAV eu-NA-ðeu ROUM'],
      ['Could you call a taxi for me?','Pourriez-vous m’appeler un taxi ?','هل يمكنك طلب سيارة أجرة لي؟','🚕','koud you KOL eu TAK-si fô MI'],
      ['Can I have the invoice?','Puis-je avoir la facture ?','هل يمكنني الحصول على الفاتورة؟','🧾','kann aï HAV ði INN-voïs']
    ],
    dialogue:[
      {scene:'À la réception'},
      {who:'Receptionist',en:'Good afternoon, welcome to the Palm Hotel.',fr:'Bonjour, bienvenue au Palm Hotel.',ar:'مساء الخير، أهلًا بك في فندق بالم.',ph:'goud âf-teu-NOUN, OUÈL-keum tou ðeu PAM ho-TÈL'},
      {me:true,choices:['Good afternoon. I have a reservation.','Good afternoon. I have a work visa.','Good afternoon. I have two bags.'],fr:'Bonjour. J’ai une réservation.',ar:'مساء الخير. لدي حجز.',ph:'goud âf-teu-NOUN. aï HAV eu rè-zeu-VÉÏ-cheun'},
      {who:'Receptionist',en:'Can I have your name and passport, please?',fr:'Votre nom et votre passeport, s’il vous plaît ?',ar:'اسمك وجواز سفرك من فضلك؟',ph:'kann aï HAV yô NÉÏM annd PÂSS-pôt, PLIZ'},
      {me:true,choices:['Karim Benali. Here is my passport.','Karim Benali. Here is the menu.','Karim Benali. Keep the change.'],fr:'Karim Benali. Voici mon passeport.',ar:'كريم بن علي. تفضل جواز سفري.',ph:'ka-RIM bè-NA-li. HIR iz maï PÂSS-pôt'},
      {who:'Receptionist',en:'Thank you. You’re in room 518.',fr:'Merci. Vous êtes dans la chambre 518.',ar:'شكرًا. غرفتك رقم 518.',ph:'þANK you. your inn ROUM FAÏV OUANN ÉÏT'},
      {me:true,choices:['Is breakfast included?','Is the rent negotiable?','Is this on offer?'],fr:'Le petit-déjeuner est-il inclus ?',ar:'هل الإفطار مشمول؟'},
      {who:'Receptionist',en:'Yes, from seven to ten thirty.',fr:'Oui, de sept heures à dix heures trente.',ar:'نعم، من السابعة حتى العاشرة والنصف.',ph:'YÈS, from SÈ-veun tou TÈN ÞEU-ti'},
      {me:true,choices:['And what time is check-out?','And what time is the flight?','And what time is the metro sign?'],fr:'Et à quelle heure faut-il libérer la chambre ?',ar:'ومتى موعد تسجيل المغادرة؟',ph:'annd OUOT TAÏM iz TCHÈK-aout'},
      {who:'Receptionist',en:'Twelve o’clock. Enjoy your stay!',fr:'À midi. Bon séjour !',ar:'الساعة الثانية عشرة. نتمنى لك إقامة ممتعة!',ph:'TOUÈLV eu-KLOK. inn-DJOÏ yô STÉÏ'},
      {me:true,choices:['Thank you very much.','You’re welcome.','Nice to meet you too.'],fr:'Merci beaucoup.',ar:'شكرًا جزيلًا.'}
    ]},
  {id:'day-mission',emoji:'🎯',kind:'mission',title:'Mission 04 — Dinner in Dubai',desc:'Réserver, commander et payer au restaurant.',
    brief:'Vous invitez un collègue au restaurant ce soir. Appelez pour réserver, commandez en signalant votre allergie aux fruits à coque, puis demandez l’addition.',
    objectives:['Réserver une table par téléphone','Demander un conseil et signaler votre allergie','Commander votre plat','Demander l’addition et payer par carte'],
    dialogue:[
      {scene:'1 · La réservation'},
      {who:'Staff',en:'Good afternoon, Al Fanar Restaurant.',fr:'Bonjour, restaurant Al Fanar.',ar:'مساء الخير، مطعم الفنار.',ph:'goud âf-teu-NOUN, al FA-nar RÈS-tront'},
      {me:true,choices:['Hello. I’d like to book a table for two.','Hello. I’d like to top up my Nol card.','Hello. I’d like to return this.'],fr:'Bonjour. Je voudrais réserver une table pour deux.',ar:'مرحبًا. أريد حجز طاولة لشخصين.',ph:'hè-LO. aïd LAÏK tou BOUK eu TÉÏ-beul fô TOU'},
      {who:'Staff',en:'For what time?',fr:'Pour quelle heure ?',ar:'لأي ساعة؟',ph:'fô OUOT TAÏM'},
      {me:true,choices:['For eight o’clock tonight, please.','For eight dirhams, please.','For eight bedrooms, please.'],fr:'Pour vingt heures ce soir, s’il vous plaît.',ar:'للساعة الثامنة هذا المساء من فضلك.',ph:'for ÉÏT eu-KLOK teu-NAÏT, PLIZ'},
      {who:'Staff',en:'Perfect. What name, please?',fr:'Parfait. À quel nom ?',ar:'ممتاز. باسم من؟',ph:'PEU-fikt. OUOT NÉÏM, PLIZ'},
      {me:true,choices:['My name is Karim Benali.','My name is Terminal 3.','My name is on offer.'],fr:'Je m’appelle Karim Benali.',ar:'اسمي كريم بن علي.',ph:'maï NÉÏM iz ka-RIM bè-NA-li'},
      {scene:'2 · À table'},
      {who:'Waiter',en:'Good evening. Are you ready to order?',fr:'Bonsoir. Vous êtes prêts à commander ?',ar:'مساء الخير. هل أنتم مستعدون للطلب؟',ph:'goud IV-ninng. â you RÈ-di tou Ô-deu'},
      {me:true,choices:['What do you recommend?','What do you do?','What is the exchange rate?'],fr:'Que recommandez-vous ?',ar:'ماذا تنصح؟'},
      {who:'Waiter',en:'The lamb machboos is our speciality.',fr:'Le machboos d’agneau est notre spécialité.',ar:'مجبوس اللحم هو طبقنا المميز.',ph:'ðeu LAM match-BOUS iz AOU-eu spè-chi-A-li-ti'},
      {me:true,choices:['Does it contain nuts? I’m allergic.','Does it have a sea view?','Does it take thirty minutes by taxi?'],fr:'Y a-t-il des fruits à coque ? Je suis allergique.',ar:'هل يحتوي على مكسرات؟ لدي حساسية.'},
      {who:'Waiter',en:'There are some almonds on top, but we can remove them.',fr:'Il y a quelques amandes dessus, mais nous pouvons les enlever.',ar:'يوجد بعض اللوز في الأعلى، لكن يمكننا إزالته.',ph:'ðèr â SAM A-meundz onn TOP, bat oui kann ri-MOUV ðèm'},
      {me:true,choices:['Yes, please, without nuts.','Yes, please, with a sea view.','Yes, please, fill it up.'],fr:'Oui, s’il vous plaît, sans fruits à coque.',ar:'نعم من فضلك، بدون مكسرات.',ph:'YÈS, PLIZ, ouið-AOUT NATS'},
      {scene:'3 · L’addition'},
      {who:'Waiter',en:'How was everything?',fr:'Tout s’est bien passé ?',ar:'كيف كان كل شيء؟',ph:'haou OUOZ ÈV-ri-þinng'},
      {me:true,choices:['Delicious, thank you. Could we have the bill, please?','Delicious, thank you. Can I see the kitchen?','Delicious, thank you. Where is the gate?'],fr:'Délicieux, merci. Pourrions-nous avoir l’addition, s’il vous plaît ?',ar:'لذيذ، شكرًا. هل يمكننا الحصول على الفاتورة من فضلك؟',ph:'di-LI-cheus, þANK you. koud oui HAV ðeu BIL, PLIZ'},
      {who:'Waiter',en:'Of course. That’s two hundred and ten dirhams.',fr:'Bien sûr. Ça fait deux cent dix dirhams.',ar:'بالتأكيد. المبلغ مئتان وعشرة دراهم.',ph:'ov KÔS. ðats TOU HAN-dreud annd TÈN DIR-hamz'},
      {me:true,choices:['Can I pay by card?','Can I see the kitchen?','Can I arrange a viewing?'],fr:'Puis-je payer par carte ?',ar:'هل يمكنني الدفع بالبطاقة؟'}
    ]}
];
