/* Parcours 2 — Live in Dubai (A1-A2) : chercher, visiter, négocier, louer.
   Format : voir parcours/README.md */
(window.EXPATIA = window.EXPATIA || {}).live = [
  {id:'live-search',emoji:'🏢',kind:'vocab',title:'Chercher un appartement',desc:'Décrire le logement que vous cherchez.',
    intro:'À Dubaï, on parle de « studio », « one-bedroom » ou « two-bedroom » : seules les chambres sont comptées, pas le salon. Les surfaces sont données en pieds carrés (square feet).',
    words:[
      ['Apartment','Appartement','شقة','🏢','eu-PART-meunt'],
      ['Studio','Studio','استوديو','🛏️','STIOU-di-o'],
      ['One-bedroom apartment','Appartement avec une chambre','شقة بغرفة نوم واحدة','🚪','OUANN-BÈD-roum eu-PART-meunt'],
      ['Furnished','Meublé','مفروشة','🛋️','FEUR-nicht'],
      ['Unfurnished','Non meublé','غير مفروشة','📦','ann-FEUR-nicht'],
      ['Villa','Villa','فيلا','🏡','VI-la'],
      ['Parking space','Place de parking','موقف سيارة','🅿️','PAR-kinng SPÉÏS'],
      ['Swimming pool','Piscine','مسبح','🏊','SOUI-minng POUL'],
      ['Gym','Salle de sport','صالة رياضية','🏋️','DJIM'],
      ['Sea view','Vue sur la mer','إطلالة على البحر','🌊','SI VIOU']
    ],
    dialogue:[
      {scene:'Au téléphone avec une agence'},
      {who:'Agent',en:'Good morning, Dubai Homes. How can I help you?',fr:'Bonjour, Dubai Homes. Comment puis-je vous aider ?',ar:'صباح الخير، دبي هومز. كيف يمكنني مساعدتك؟',ph:'goud MOR-ninng, dou-BAÏ HOMZ. haou kann aï HÈLP you'},
      {me:true,choices:['I’m looking for an apartment.','I’m looking for my passport.','I’d like a table for two.'],fr:'Je cherche un appartement.',ar:'أبحث عن شقة.',ph:'aïm LOU-kinng for ann eu-PART-meunt'},
      {who:'Agent',en:'Sure. How many bedrooms?',fr:'Bien sûr. Combien de chambres ?',ar:'بالتأكيد. كم غرفة نوم؟',ph:'CHOR. haou MÈ-ni BÈD-roumz'},
      {me:true,choices:['One bedroom, please.','One euro, please.','Two weeks, please.'],fr:'Une chambre, s’il vous plaît.',ar:'غرفة نوم واحدة من فضلك.',ph:'OUANN BÈD-roum, PLIZ'},
      {who:'Agent',en:'Furnished or unfurnished?',fr:'Meublé ou non meublé ?',ar:'مفروشة أم غير مفروشة؟',ph:'FEUR-nicht or ann-FEUR-nicht'},
      {me:true,choices:['Furnished, with a parking space.','Furnished, with a receipt.','Unfurnished, with a flight.'],fr:'Meublé, avec une place de parking.',ar:'مفروشة، مع موقف سيارة.',ph:'FEUR-nicht, ouið eu PAR-kinng SPÉÏS'},
      {who:'Agent',en:'We have a nice one in Dubai Marina, with a gym and a swimming pool.',fr:'Nous en avons un bien à Dubai Marina, avec salle de sport et piscine.',ar:'لدينا شقة جميلة في دبي مارينا، مع صالة رياضية ومسبح.',ph:'oui HAV eu NAÏS OUANN inn dou-BAÏ ma-RI-na, ouið eu DJIM annd eu SOUI-minng POUL'},
      {me:true,choices:['Great! Can you send me some photos?','Great! Where is the metro sign?','Great! I’m an engineer.'],fr:'Parfait ! Pouvez-vous m’envoyer des photos ?',ar:'رائع! هل يمكنك أن ترسل لي بعض الصور؟',ph:'GRÉÏT ! kann you SÈND mi sam FO-toz'}
    ]},
  {id:'live-price',emoji:'💰',kind:'phrases',title:'Demander le prix',desc:'Loyer, chèques, dépôt, frais d’agence.',
    intro:'À Dubaï, le loyer est le plus souvent annoncé à l’année et payé en plusieurs chèques. Prévoyez aussi un dépôt de garantie et la commission de l’agence.',
    words:[
      ['How much is the rent?','Combien coûte le loyer ?','كم الإيجار؟','💰','haou MATCH iz ðeu RÈNT'],
      ['Is it per year or per month?','C’est par an ou par mois ?','هل هو سنوي أم شهري؟','📅','iz it peur YIR or peur MANþ'],
      ['How many cheques?','En combien de chèques ?','كم عدد الشيكات؟','🧾','haou MÈ-ni TCHÈKS'],
      ['How much is the deposit?','Combien est le dépôt de garantie ?','كم مبلغ التأمين؟','🔐','haou MATCH iz ðeu di-PO-zit'],
      ['Is there an agency fee?','Y a-t-il des frais d’agence ?','هل توجد عمولة للوكالة؟','🏢','iz ðèr ann ÉÏ-djeun-si FI'],
      ['Are bills included?','Les charges sont-elles incluses ?','هل الفواتير مشمولة؟','💡','ar BILZ inn-KLOU-did'],
      ['Is the rent negotiable?','Le loyer est-il négociable ?','هل الإيجار قابل للتفاوض؟','🤝','iz ðeu RÈNT ni-GO-chi-eu-beul'],
      ['What is the total cost?','Quel est le coût total ?','ما هي التكلفة الإجمالية؟','🧮','OUOT iz ðeu TO-teul KOST']
    ],
    dialogue:[
      {scene:'Avec l’agent immobilier'},
      {who:'Agent',en:'The rent is eighty thousand dirhams.',fr:'Le loyer est de quatre-vingt mille dirhams.',ar:'الإيجار ثمانون ألف درهم.',ph:'ðeu RÈNT iz ÉÏ-ti þAOU-zeund DIR-hamz'},
      {me:true,choices:['Is it per year or per month?','Is it furnished or a flight?','Is it your passport?'],fr:'C’est par an ou par mois ?',ar:'هل هو سنوي أم شهري؟'},
      {who:'Agent',en:'Per year, in four cheques.',fr:'Par an, en quatre chèques.',ar:'سنويًا، على أربعة شيكات.',ph:'peur YIR, inn FOR TCHÈKS'},
      {me:true,choices:['How much is the deposit?','How much is the menu?','How long is the flight?'],fr:'Combien est le dépôt de garantie ?',ar:'كم مبلغ التأمين؟'},
      {who:'Agent',en:'Five percent, so four thousand dirhams.',fr:'Cinq pour cent, donc quatre mille dirhams.',ar:'خمسة بالمئة، أي أربعة آلاف درهم.',ph:'FAÏV peur-SÈNT, so FOR þAOU-zeund DIR-hamz'},
      {me:true,choices:['Are bills included?','Are you new here?','Are you going to Dubai Marina?'],fr:'Les charges sont-elles incluses ?',ar:'هل الفواتير مشمولة؟'},
      {who:'Agent',en:'No, electricity and water are not included.',fr:'Non, l’électricité et l’eau ne sont pas incluses.',ar:'لا، الكهرباء والماء غير مشمولة.',ph:'NO, i-lèk-TRI-si-ti annd OUO-teur ar NOT inn-KLOU-did'},
      {me:true,choices:['Is the rent negotiable?','Is the metro on the first floor?','Is this your first visit?'],fr:'Le loyer est-il négociable ?',ar:'هل الإيجار قابل للتفاوض؟'},
      {who:'Agent',en:'Maybe. The landlord could accept seventy-five thousand.',fr:'Peut-être. Le propriétaire pourrait accepter soixante-quinze mille.',ar:'ربما. قد يقبل المالك خمسة وسبعين ألفًا.',ph:'MÉÏ-bi. ðeu LANND-lord koud ak-SÈPT SÈ-veun-ti-FAÏV þAOU-zeund'}
    ]},
  {id:'live-visit',emoji:'🔑',kind:'phrases',title:'Visiter et négocier',desc:'Organiser une visite, poser vos questions, négocier.',
    words:[
      ['Can I arrange a viewing?','Puis-je organiser une visite ?','هل يمكنني ترتيب موعد لمعاينة الشقة؟','📅','kann aï eu-RÉÏNDJ eu VIOU-inng'],
      ['When is it available?','Quand est-il disponible ?','متى تكون متاحة؟','🗓️','OUÈN iz it eu-VÉÏ-leu-beul'],
      ['Can I see the kitchen?','Puis-je voir la cuisine ?','هل يمكنني رؤية المطبخ؟','🍳','kann aï SI ðeu KI-tcheun'],
      ['Is the air conditioning included?','La climatisation est-elle comprise ?','هل التكييف مشمول؟','❄️','iz ði ÈR keun-DI-cheu-ninng inn-KLOU-did'],
      ['Can you lower the price?','Pouvez-vous baisser le prix ?','هل يمكنك تخفيض السعر؟','📉','kann you LO-eur ðeu PRAÏS'],
      ['Can I pay in two cheques?','Puis-je payer en deux chèques ?','هل يمكنني الدفع على شيكين؟','🧾','kann aï PÉÏ inn TOU TCHÈKS'],
      ['I’ll think about it.','Je vais réfléchir.','سأفكر في الأمر.','🤔','aïl þINNK eu-BAOUT it'],
      ['I’ll take it.','Je le prends.','سآخذها.','✅','aïl TÉÏK it']
    ],
    dialogue:[
      {scene:'Visite de l’appartement'},
      {who:'Agent',en:'Here is the living room. It has a lot of light.',fr:'Voici le salon. Il est très lumineux.',ar:'هذه غرفة المعيشة. فيها الكثير من الضوء.',ph:'HIR iz ðeu LI-vinng ROUM. it haz eu LOT ov LAÏT'},
      {me:true,choices:['It’s nice. Can I see the kitchen?','It’s nice. Can I see your passport?','It’s nice. Keep the change.'],fr:'C’est joli. Puis-je voir la cuisine ?',ar:'إنها جميلة. هل يمكنني رؤية المطبخ؟',ph:'its NAÏS. kann aï SI ðeu KI-tcheun'},
      {who:'Agent',en:'Of course, this way.',fr:'Bien sûr, par ici.',ar:'بالتأكيد، من هنا.',ph:'ov KORS, ðis OUÉÏ'},
      {me:true,choices:['When is it available?','When is the flight?','When is your birthday?'],fr:'Quand est-il disponible ?',ar:'متى تكون متاحة؟'},
      {who:'Agent',en:'From the first of next month.',fr:'À partir du premier du mois prochain.',ar:'ابتداءً من أول الشهر القادم.',ph:'from ðeu FEURST ov NÈKST MANþ'},
      {me:true,choices:['Can you lower the price?','Can you lower the music?','Can you open a bank account?'],fr:'Pouvez-vous baisser le prix ?',ar:'هل يمكنك تخفيض السعر؟'},
      {who:'Agent',en:'I can ask the landlord for seventy-five thousand.',fr:'Je peux demander soixante-quinze mille au propriétaire.',ar:'يمكنني أن أطلب من المالك خمسة وسبعين ألفًا.',ph:'aï kann ASK ðeu LANND-lord for SÈ-veun-ti-FAÏV þAOU-zeund'},
      {me:true,choices:['Great. Can I pay in two cheques?','Great. Can I have the menu?','Great. Where is the gate?'],fr:'Parfait. Puis-je payer en deux chèques ?',ar:'رائع. هل يمكنني الدفع على شيكين؟',ph:'GRÉÏT. kann aï PÉÏ inn TOU TCHÈKS'},
      {who:'Agent',en:'Yes, that’s possible.',fr:'Oui, c’est possible.',ar:'نعم، هذا ممكن.',ph:'YÈS, ðats PO-si-beul'},
      {me:true,choices:['Perfect. I’ll take it.','Perfect. I’m from Morocco.','Perfect. Stop here, please.'],fr:'Parfait. Je le prends.',ar:'ممتاز. سآخذها.',ph:'PEUR-fikt. aïl TÉÏK it'}
    ]},
  {id:'live-problems',emoji:'🔧',kind:'mixed',title:'Problèmes dans le logement',desc:'Climatisation, fuite, électricité : signaler une panne.',
    intro:'En cas de panne, contactez la maintenance de l’immeuble ou votre propriétaire. L’électricité et l’eau sont fournies par DEWA.',
    words:[
      ['The air conditioning isn’t working.','La climatisation ne marche pas.','التكييف لا يعمل.','🥵','ði ÈR keun-DI-cheu-ninng IZ-eunt WEUR-kinng'],
      ['There’s a water leak.','Il y a une fuite d’eau.','يوجد تسرب للماء.','💧','ðèrz eu OUO-teur LIK'],
      ['There’s no electricity.','Il n’y a pas d’électricité.','لا توجد كهرباء.','🔌','ðèrz NO i-lèk-TRI-si-ti'],
      ['The lift is broken.','L’ascenseur est en panne.','المصعد معطل.','🛗','ðeu LIFT iz BRO-keun'],
      ['Maintenance','Maintenance (service technique)','الصيانة','🔧','MÉÏN-teu-neuns'],
      ['Landlord','Propriétaire (bailleur)','المالك','🧑‍💼','LANND-lord'],
      ['When can someone come?','Quand quelqu’un peut-il passer ?','متى يمكن أن يأتي أحد؟','🕐','OUÈN kann SAM-ouann KAM'],
      ['It’s urgent.','C’est urgent.','الأمر عاجل.','🚨','its EUR-djeunt']
    ],
    dialogue:[
      {scene:'Appel à la maintenance'},
      {who:'Staff',en:'Building maintenance, good morning.',fr:'Maintenance de l’immeuble, bonjour.',ar:'صيانة المبنى، صباح الخير.',ph:'BIL-dinng MÉÏN-teu-neuns, goud MOR-ninng'},
      {me:true,choices:['Hello, the air conditioning isn’t working.','Hello, I’d like a SIM card.','Hello, I’m here on holiday.'],fr:'Bonjour, la climatisation ne marche pas.',ar:'مرحبًا، التكييف لا يعمل.',ph:'hè-LO, ði ÈR keun-DI-cheu-ninng IZ-eunt WEUR-kinng'},
      {who:'Staff',en:'What is your apartment number?',fr:'Quel est le numéro de votre appartement ?',ar:'ما رقم شقتك؟',ph:'OUOT iz yor eu-PART-meunt NAM-beur'},
      {me:true,choices:['Apartment 1204, on the twelfth floor.','Belt number five, on your right.','Terminal 3, please.'],fr:'Appartement 1204, au douzième étage.',ar:'الشقة 1204، في الطابق الثاني عشر.',ph:'eu-PART-meunt TOUÈLV O FOR, onn ðeu TOUÈLFþ FLOR'},
      {who:'Staff',en:'OK. We can send a technician tomorrow morning.',fr:'D’accord. Nous pouvons envoyer un technicien demain matin.',ar:'حسنًا. يمكننا إرسال فني صباح الغد.',ph:'o-KÉÏ. oui kann SÈND eu tèk-NI-cheun teu-MO-ro MOR-ninng'},
      {me:true,choices:['It’s very hot. It’s urgent.','It’s very nice. Nice to meet you.','It’s eighty dirhams.'],fr:'Il fait très chaud. C’est urgent.',ar:'الجو حار جدًا. الأمر عاجل.',ph:'its VÈ-ri HOT. its EUR-djeunt'},
      {who:'Staff',en:'I understand. Someone will come this afternoon.',fr:'Je comprends. Quelqu’un passera cet après-midi.',ar:'أفهم. سيأتي أحدهم بعد ظهر اليوم.',ph:'aï ann-deur-STANND. SAM-ouann ouil KAM ðis af-teur-NOUN'},
      {me:true,choices:['Thank you very much.','You’re welcome.','Welcome to Dubai.'],fr:'Merci beaucoup.',ar:'شكرًا جزيلًا.'}
    ]},
  {id:'live-mission',emoji:'🎯',kind:'mission',title:'Mission 02 — Find an apartment',desc:'Appeler, visiter et négocier votre logement.',
    brief:'Vous avez vu une annonce pour un appartement meublé d’une chambre à Dubai Marina. Appelez l’agent, posez les bonnes questions sur le prix, organisez une visite, puis négociez le loyer.',
    objectives:['Appeler l’agent et dire ce que vous cherchez','Demander le loyer, le nombre de chèques, le dépôt et les frais','Organiser une visite','Négocier et conclure'],
    dialogue:[
      {scene:'1 · L’appel'},
      {who:'Agent',en:'Hello, Marina Properties. How can I help?',fr:'Bonjour, Marina Properties. Que puis-je faire pour vous ?',ar:'مرحبًا، مارينا بروبرتيز. كيف يمكنني المساعدة؟',ph:'hè-LO, ma-RI-na PRO-peur-tiz. haou kann aï HÈLP'},
      {me:true,choices:['I’m calling about the one-bedroom apartment in Dubai Marina.','I’m calling about my luggage.','I’m calling about the exchange rate.'],fr:'J’appelle au sujet de l’appartement d’une chambre à Dubai Marina.',ar:'أتصل بخصوص الشقة ذات غرفة النوم الواحدة في دبي مارينا.',ph:'aïm KO-linng eu-BAOUT ði OUANN-BÈD-roum eu-PART-meunt inn dou-BAÏ ma-RI-na'},
      {who:'Agent',en:'Yes, it’s still available. It’s furnished, with a sea view.',fr:'Oui, il est toujours disponible. Il est meublé, avec vue sur la mer.',ar:'نعم، ما زالت متاحة. إنها مفروشة، مع إطلالة على البحر.',ph:'YÈS, its STIL eu-VÉÏ-leu-beul. its FEUR-nicht, ouið eu SI VIOU'},
      {me:true,choices:['How much is the rent?','How much is the taxi?','How much data is included?'],fr:'Combien coûte le loyer ?',ar:'كم الإيجار؟'},
      {who:'Agent',en:'Ninety thousand dirhams per year.',fr:'Quatre-vingt-dix mille dirhams par an.',ar:'تسعون ألف درهم سنويًا.',ph:'NAÏN-ti þAOU-zeund DIR-hamz peur YIR'},
      {me:true,choices:['How many cheques?','How many brothers?','How many bags?'],fr:'En combien de chèques ?',ar:'كم عدد الشيكات؟'},
      {who:'Agent',en:'Four cheques. The deposit is five percent.',fr:'Quatre chèques. Le dépôt est de cinq pour cent.',ar:'أربعة شيكات. التأمين خمسة بالمئة.',ph:'FOR TCHÈKS. ðeu di-PO-zit iz FAÏV peur-SÈNT'},
      {me:true,choices:['Is there an agency fee?','Is there a prayer room?','Is there a pharmacy?'],fr:'Y a-t-il des frais d’agence ?',ar:'هل توجد عمولة للوكالة؟'},
      {who:'Agent',en:'Yes, five percent.',fr:'Oui, cinq pour cent.',ar:'نعم، خمسة بالمئة.',ph:'YÈS, FAÏV peur-SÈNT'},
      {me:true,choices:['Can I arrange a viewing?','Can I pay by cash at the gate?','Can I have the Wi-Fi password?'],fr:'Puis-je organiser une visite ?',ar:'هل يمكنني ترتيب موعد لمعاينة الشقة؟'},
      {who:'Agent',en:'Sure. Tomorrow at six p.m.?',fr:'Bien sûr. Demain à dix-huit heures ?',ar:'بالتأكيد. غدًا الساعة السادسة مساءً؟',ph:'CHOR. teu-MO-ro at SIKS pi-ÈM'},
      {me:true,choices:['Yes, tomorrow at six is perfect.','Yes, six dirhams is perfect.','Yes, six bags is perfect.'],fr:'Oui, demain à dix-huit heures, c’est parfait.',ar:'نعم، غدًا الساعة السادسة مناسب تمامًا.',ph:'YÈS, teu-MO-ro at SIKS iz PEUR-fikt'},
      {scene:'2 · La visite'},
      {who:'Agent',en:'So, what do you think?',fr:'Alors, qu’en pensez-vous ?',ar:'إذن، ما رأيك؟',ph:'SO, OUOT dou you þINNK'},
      {me:true,choices:['I like it. Is the rent negotiable?','I like it. Is it your first visit?','I like it. Where is my luggage?'],fr:'Il me plaît. Le loyer est-il négociable ?',ar:'أعجبتني. هل الإيجار قابل للتفاوض؟',ph:'aï LAÏK it. iz ðeu RÈNT ni-GO-chi-eu-beul'},
      {who:'Agent',en:'The landlord could accept eighty-five thousand.',fr:'Le propriétaire pourrait accepter quatre-vingt-cinq mille.',ar:'قد يقبل المالك خمسة وثمانين ألفًا.',ph:'ðeu LANND-lord koud ak-SÈPT ÉÏ-ti-FAÏV þAOU-zeund'},
      {me:true,choices:['OK. Can I pay in two cheques?','OK. Can I see the menu?','OK. Can I change 500 euros?'],fr:'D’accord. Puis-je payer en deux chèques ?',ar:'حسنًا. هل يمكنني الدفع على شيكين؟',ph:'o-KÉÏ. kann aï PÉÏ inn TOU TCHÈKS'},
      {who:'Agent',en:'Yes, that’s fine.',fr:'Oui, c’est d’accord.',ar:'نعم، لا بأس.',ph:'YÈS, ðats FAÏN'},
      {me:true,choices:['Perfect. I’ll take it.','Perfect. I’ll think about the flight.','Perfect. Nice to meet you too.'],fr:'Parfait. Je le prends.',ar:'ممتاز. سآخذها.'},
      {who:'Agent',en:'Great! I’ll prepare the contract.',fr:'Parfait ! Je prépare le contrat.',ar:'رائع! سأجهز العقد.',ph:'GRÉÏT ! aïl pri-PÈR ðeu KONN-trakt'}
    ]}
];
