/* Parcours 10 — Professional & Social English (B1-B2) : rencontres, réservations, téléphone.
   Format : voir parcours/README.md */
(window.EXPATIA = window.EXPATIA || {}).social = [
  {id:'soc-meet',emoji:'🤝',kind:'phrases',title:'Rencontrer des gens',desc:'Faire connaissance, inviter, accepter ou refuser.',
    words:[
      ['Where are you from originally?','D’où venez-vous à l’origine ?','من أين أنت في الأصل؟','🌍','OUÈR ar you from eu-RI-dji-neu-li'],
      ['How long have you been in Dubai?','Depuis combien de temps êtes-vous à Dubaï ?','منذ متى وأنت في دبي؟','⏳','haou LONNG hav you BIN inn dou-BAÏ'],
      ['What do you do for a living?','Que faites-vous dans la vie ?','ماذا تعمل؟','💼','OUOT dou you DOU for eu LI-vinng'],
      ['Would you like to join us for dinner?','Voulez-vous dîner avec nous ?','هل تود أن تنضم إلينا على العشاء؟','🍽️','woud you LAÏK tou DJOÏN as for DI-neur'],
      ['I’d love to, thank you.','Avec plaisir, merci.','بكل سرور، شكرًا.','😊','aïd LAV tou, þANK you'],
      ['I’m sorry, I can’t make it.','Désolé(e), je ne peux pas venir.','آسف، لا أستطيع الحضور.','🙏','aïm SO-ri, aï KANT MÉÏK it'],
      ['Let’s keep in touch.','Restons en contact.','لنبقَ على تواصل.','📱','lèts KIP inn TATCH'],
      ['Can I have your number?','Puis-je avoir votre numéro ?','هل يمكنني الحصول على رقمك؟','☎️','kann aï HAV yor NAM-beur']
    ],
    dialogue:[
      {scene:'Soirée entre expatriés'},
      {who:'Guest',en:'Hi, I’m Daniel. I don’t think we’ve met.',fr:'Bonjour, je suis Daniel. Je crois que nous ne nous connaissons pas.',ar:'مرحبًا، أنا دانيال. لا أظن أننا التقينا من قبل.',ph:'HAÏ, aïm DA-nieul. aï DONT þINNK ouiv MÈT'},
      {me:true,choices:['Nice to meet you, I’m Karim.','Nice to meet you, it’s urgent.','Nice to meet you, fill it up.'],fr:'Enchanté, je suis Karim.',ar:'تشرفت بمعرفتك، أنا كريم.',ph:'NAÏS tou MIT you, aïm ka-RIM'},
      {who:'Guest',en:'How long have you been in Dubai?',fr:'Depuis combien de temps êtes-vous à Dubaï ?',ar:'منذ متى وأنت في دبي؟'},
      {me:true,choices:['Six months. And you?','Six dirhams. And you?','Six stops. And you?'],fr:'Six mois. Et vous ?',ar:'ستة أشهر. وأنت؟',ph:'SIKS MANþS. annd YOU'},
      {who:'Guest',en:'Three years. What do you do for a living?',fr:'Trois ans. Que faites-vous dans la vie ?',ar:'ثلاث سنوات. ماذا تعمل؟',ph:'þRI YIRZ. OUOT dou you DOU for eu LI-vinng'},
      {me:true,choices:['I run a small consulting company.','I run to the petrol station.','I run a fever.'],fr:'Je dirige une petite société de conseil.',ar:'أدير شركة استشارات صغيرة.',ph:'aï RANN eu SMOL keun-SAL-tinng KAMM-peu-ni'},
      {who:'Guest',en:'Interesting! Would you like to join us for dinner on Friday?',fr:'Intéressant ! Voulez-vous dîner avec nous vendredi ?',ar:'مثير للاهتمام! هل تود أن تنضم إلينا على العشاء يوم الجمعة؟',ph:'INN-treus-tinng ! woud you LAÏK tou DJOÏN as for DI-neur onn FRAÏ-déï'},
      {me:true,choices:['I’d love to, thank you. Can I have your number?','I’d love to, thank you. Can I have the invoice?','I’d love to, thank you. Can I have a quote?'],fr:'Avec plaisir, merci. Puis-je avoir votre numéro ?',ar:'بكل سرور، شكرًا. هل يمكنني الحصول على رقمك؟',ph:'aïd LAV tou, þANK you. kann aï HAV yor NAM-beur'},
      {who:'Guest',en:'Sure, I’ll send you a message.',fr:'Bien sûr, je vous envoie un message.',ar:'بالتأكيد، سأرسل لك رسالة.',ph:'CHOR, aïl SÈND you eu MÈ-sidj'}
    ]},
  {id:'soc-book',emoji:'🎟️',kind:'phrases',title:'Réservations et sorties',desc:'Excursion, spa, salle de sport, billets.',
    words:[
      ['I’d like to book a desert safari for two.','Je voudrais réserver un safari dans le désert pour deux.','أريد حجز رحلة سفاري في الصحراء لشخصين.','🐪','aïd LAÏK tou BOUK eu DÈ-zeurt seu-FA-ri for TOU'],
      ['Is hotel pick-up included?','La prise en charge à l’hôtel est-elle incluse ?','هل التوصيل من الفندق مشمول؟','🚐','iz ho-TÈL PIK-ap inn-KLOU-did'],
      ['What time does it start?','À quelle heure ça commence ?','متى يبدأ؟','🕓','OUOT TAÏM deuz it START'],
      ['Are there any tickets left for Saturday?','Reste-t-il des billets pour samedi ?','هل بقيت تذاكر ليوم السبت؟','🎫','ar ðèr È-ni TI-kits LÈFT for SA-teur-déï'],
      ['I’d like to book a massage at the spa.','Je voudrais réserver un massage au spa.','أريد حجز جلسة تدليك في السبا.','💆','aïd LAÏK tou BOUK eu MA-saj at ðeu SPA'],
      ['How much is a monthly gym membership?','Combien coûte l’abonnement mensuel à la salle de sport ?','كم الاشتراك الشهري في الصالة الرياضية؟','🏋️','haou MATCH iz eu MANþ-li DJIM MÈM-beur-chip'],
      ['Can I cancel for free?','Puis-je annuler gratuitement ?','هل يمكنني الإلغاء مجانًا؟','↩️','kann aï KANN-seul for FRI'],
      ['Is there a dress code?','Y a-t-il un code vestimentaire ?','هل توجد قواعد للباس؟','👔','iz ðèr eu DRÈS KOD']
    ],
    dialogue:[
      {scene:'À l’agence d’excursions'},
      {who:'Agent',en:'Hello! What can I book for you?',fr:'Bonjour ! Que puis-je réserver pour vous ?',ar:'مرحبًا! ماذا يمكنني أن أحجز لك؟',ph:'hè-LO ! OUOT kann aï BOUK for you'},
      {me:true,choices:['I’d like to book a desert safari for two.','I’d like to book a medical test.','I’d like to book the engine light.'],fr:'Je voudrais réserver un safari dans le désert pour deux.',ar:'أريد حجز رحلة سفاري في الصحراء لشخصين.'},
      {who:'Agent',en:'Sure. This Saturday?',fr:'Bien sûr. Ce samedi ?',ar:'بالتأكيد. يوم السبت هذا؟',ph:'CHOR. ðis SA-teur-déï'},
      {me:true,choices:['Yes. What time does it start?','Yes. What time is check-out?','Yes. What time is the meeting?'],fr:'Oui. À quelle heure ça commence ?',ar:'نعم. متى يبدأ؟',ph:'YÈS. OUOT TAÏM deuz it START'},
      {who:'Agent',en:'We pick you up at three p.m. and you’re back at nine.',fr:'Nous venons vous chercher à quinze heures et vous êtes de retour à vingt et une heures.',ar:'نأخذك في الساعة الثالثة عصرًا وتعود في التاسعة مساءً.',ph:'oui PIK you AP at þRI pi-ÈM annd your BAK at NAÏN'},
      {me:true,choices:['Is hotel pick-up included?','Is housing allowance included?','Is the air conditioning included?'],fr:'La prise en charge à l’hôtel est-elle incluse ?',ar:'هل التوصيل من الفندق مشمول؟'},
      {who:'Agent',en:'Yes, and dinner too. It’s three hundred dirhams per person.',fr:'Oui, et le dîner aussi. C’est trois cents dirhams par personne.',ar:'نعم، والعشاء أيضًا. السعر ثلاثمئة درهم للشخص.',ph:'YÈS, annd DI-neur TOU. its þRI HAN-dreud DIR-hamz peur PEUR-seun'},
      {me:true,choices:['Can I cancel for free?','Can I cancel the rent?','Can I cancel my Emirates ID?'],fr:'Puis-je annuler gratuitement ?',ar:'هل يمكنني الإلغاء مجانًا؟'},
      {who:'Agent',en:'Yes, up to twenty-four hours before.',fr:'Oui, jusqu’à vingt-quatre heures avant.',ar:'نعم، حتى أربع وعشرين ساعة قبل الموعد.',ph:'YÈS, AP tou touèn-ti-FOR AOU-eurz bi-FOR'},
      {me:true,choices:['Perfect. I’ll take it.','Perfect. I’m from Morocco.','Perfect. Stop here, please.'],fr:'Parfait. Je réserve.',ar:'ممتاز. سأحجز.'}
    ]},
  {id:'soc-phone',emoji:'📞',kind:'phrases',title:'Téléphoner et prendre rendez-vous',desc:'Prendre, déplacer, annuler un rendez-vous par téléphone.',
    intro:'Au téléphone, on a le droit de demander de répéter ou de parler plus lentement : c’est normal, même pour les anglophones, surtout quand la ligne est mauvaise.',
    words:[
      ['I’d like to make an appointment.','Je voudrais prendre rendez-vous.','أريد تحديد موعد.','📅','aïd LAÏK tou MÉÏK ann eu-POÏNT-meunt'],
      ['Are you available tomorrow?','Êtes-vous disponible demain ?','هل أنت متاح غدًا؟','🗓️','ar you eu-VÉÏ-leu-beul teu-MO-ro'],
      ['What time works for you?','Quelle heure vous convient ?','ما الوقت المناسب لك؟','🕐','OUOT TAÏM WEURKS for you'],
      ['I’d like to reschedule.','Je voudrais déplacer le rendez-vous.','أريد تغيير الموعد.','🔄','aïd LAÏK tou ri-CHÈ-djoul'],
      ['I’d like to cancel my appointment.','Je voudrais annuler mon rendez-vous.','أريد إلغاء موعدي.','❌','aïd LAÏK tou KANN-seul maï eu-POÏNT-meunt'],
      ['Could you speak more slowly, please?','Pourriez-vous parler plus lentement, s’il vous plaît ?','هل يمكنك التحدث ببطء أكثر من فضلك؟','🐢','koud you SPIK MOR SLO-li, PLIZ'],
      ['Sorry, the line is bad.','Désolé(e), la ligne est mauvaise.','آسف، الخط سيئ.','📶','SO-ri, ðeu LAÏN iz BAD'],
      ['Can I leave a message?','Puis-je laisser un message ?','هل يمكنني ترك رسالة؟','📝','kann aï LIV eu MÈ-sidj']
    ],
    dialogue:[
      {scene:'Appel au garage'},
      {who:'Receptionist',en:'Good morning, Speedy Motors.',fr:'Bonjour, Speedy Motors.',ar:'صباح الخير، سبيدي موتورز.',ph:'goud MOR-ninng, SPI-di MO-teurz'},
      {me:true,choices:['Hello, I’d like to make an appointment for my car.','Hello, I’d like to make an offer.','Hello, I’d like to make a transfer abroad.'],fr:'Bonjour, je voudrais prendre rendez-vous pour ma voiture.',ar:'مرحبًا، أريد تحديد موعد لسيارتي.',ph:'hè-LO, aïd LAÏK tou MÉÏK ann eu-POÏNT-meunt for maï KAR'},
      {who:'Receptionist',en:'Sure. What time works for you?',fr:'Bien sûr. Quelle heure vous convient ?',ar:'بالتأكيد. ما الوقت المناسب لك؟',ph:'CHOR. OUOT TAÏM WEURKS for you'},
      {me:true,choices:['Are you available tomorrow morning?','Are you allergic to nuts?','Are you new here?'],fr:'Êtes-vous disponibles demain matin ?',ar:'هل أنتم متاحون صباح الغد؟',ph:'ar you eu-VÉÏ-leu-beul teu-MO-ro MOR-ninng'},
      {who:'Receptionist',en:'Tomorrow at nine thirty?',fr:'Demain à neuf heures trente ?',ar:'غدًا الساعة التاسعة والنصف؟',ph:'teu-MO-ro at NAÏN ÞEUR-ti'},
      {me:true,choices:['Sorry, the line is bad. Could you speak more slowly, please?','Sorry, the rent is negotiable.','Sorry, the tyres are fine.'],fr:'Désolé, la ligne est mauvaise. Pourriez-vous parler plus lentement, s’il vous plaît ?',ar:'آسف، الخط سيئ. هل يمكنك التحدث ببطء أكثر من فضلك؟',ph:'SO-ri, ðeu LAÏN iz BAD. koud you SPIK MOR SLO-li, PLIZ'},
      {who:'Receptionist',en:'Of course. Tomorrow… at nine… thirty.',fr:'Bien sûr. Demain… à neuf heures… trente.',ar:'بالتأكيد. غدًا… الساعة التاسعة… والنصف.',ph:'ov KORS. teu-MO-ro… at NAÏN… ÞEUR-ti'},
      {me:true,choices:['Perfect, see you tomorrow.','Perfect, see you last year.','Perfect, keep the change.'],fr:'Parfait, à demain.',ar:'ممتاز، أراكم غدًا.',ph:'PEUR-fikt, SI you teu-MO-ro'},
      {scene:'Le lendemain matin'},
      {who:'Receptionist',en:'Speedy Motors, good morning.',fr:'Speedy Motors, bonjour.',ar:'سبيدي موتورز، صباح الخير.',ph:'SPI-di MO-teurz, goud MOR-ninng'},
      {me:true,choices:['Hello, I’d like to reschedule my appointment.','Hello, I’d like to reschedule the rice.','Hello, I’d like to reschedule my fever.'],fr:'Bonjour, je voudrais déplacer mon rendez-vous.',ar:'مرحبًا، أريد تغيير موعدي.',ph:'hè-LO, aïd LAÏK tou ri-CHÈ-djoul maï eu-POÏNT-meunt'},
      {who:'Receptionist',en:'No problem. Is Thursday OK?',fr:'Pas de problème. Jeudi, ça vous va ?',ar:'لا مشكلة. هل يناسبك يوم الخميس؟',ph:'NO PRO-bleum. iz þEURZ-déï o-KÉÏ'},
      {me:true,choices:['Yes, Thursday is fine. Thank you.','Yes, Thursday is a virus.','Yes, Thursday is furnished.'],fr:'Oui, jeudi me convient. Merci.',ar:'نعم، الخميس مناسب. شكرًا.',ph:'YÈS, þEURZ-déï iz FAÏN. þANK you'}
    ]},
  {id:'soc-mission',emoji:'🎯',kind:'mission',title:'Mission 10 — Plan your weekend',desc:'Accepter une invitation, réserver, déplacer un rendez-vous.',
    brief:'Un collègue vous propose un safari dans le désert samedi avec d’autres expatriés. Acceptez l’invitation, réservez l’excursion pour le groupe, puis déplacez votre rendez-vous chez le dentiste, prévu le même jour.',
    objectives:['Accepter l’invitation','Réserver l’activité et poser les bonnes questions','Déplacer un rendez-vous par téléphone'],
    dialogue:[
      {scene:'1 · L’invitation'},
      {who:'Colleague',en:'We’re going on a desert safari on Saturday. Would you like to come?',fr:'Nous faisons un safari dans le désert samedi. Tu veux venir ?',ar:'سنذهب في رحلة سفاري في الصحراء يوم السبت. هل تود المجيء؟',ph:'ouir GO-inng onn eu DÈ-zeurt seu-FA-ri onn SA-teur-déï. woud you LAÏK tou KAM'},
      {me:true,choices:['I’d love to, thank you!','I’d love to, fill it up!','I’d love to, it’s urgent!'],fr:'Avec plaisir, merci !',ar:'بكل سرور، شكرًا!',ph:'aïd LAV tou, þANK you'},
      {who:'Colleague',en:'Great! Can you book it for the four of us?',fr:'Super ! Tu peux réserver pour nous quatre ?',ar:'رائع! هل يمكنك الحجز لنا نحن الأربعة؟',ph:'GRÉÏT ! kann you BOUK it for ðeu FOR ov as'},
      {me:true,choices:['Sure, I’ll call the agency.','Sure, I’ll call an ambulance.','Sure, I’ll call the landlord.'],fr:'Bien sûr, j’appelle l’agence.',ar:'بالتأكيد، سأتصل بالوكالة.',ph:'CHOR, aïl KOL ði ÉÏ-djeun-si'},
      {scene:'2 · La réservation'},
      {who:'Agent',en:'Desert Dreams, how can I help?',fr:'Desert Dreams, que puis-je faire pour vous ?',ar:'ديزرت دريمز، كيف يمكنني المساعدة؟',ph:'DÈ-zeurt DRIMZ, haou kann aï HÈLP'},
      {me:true,choices:['I’d like to book a desert safari for four people on Saturday.','I’d like to book a medical test for four.','I’d like to book four cheques.'],fr:'Je voudrais réserver un safari dans le désert pour quatre personnes samedi.',ar:'أريد حجز رحلة سفاري في الصحراء لأربعة أشخاص يوم السبت.',ph:'aïd LAÏK tou BOUK eu DÈ-zeurt seu-FA-ri for FOR PI-peul onn SA-teur-déï'},
      {who:'Agent',en:'Let me check… Yes, we have four places left.',fr:'Je vérifie… Oui, il nous reste quatre places.',ar:'دعني أتحقق… نعم، بقيت لدينا أربعة أماكن.',ph:'lèt mi TCHÈK… YÈS, oui HAV FOR PLÉÏ-siz LÈFT'},
      {me:true,choices:['Great. Is hotel pick-up included?','Great. Is housing allowance included?','Great. Is the engine light on?'],fr:'Parfait. La prise en charge à l’hôtel est-elle incluse ?',ar:'رائع. هل التوصيل من الفندق مشمول؟',ph:'GRÉÏT. iz ho-TÈL PIK-ap inn-KLOU-did'},
      {who:'Agent',en:'Yes, from anywhere in Dubai.',fr:'Oui, depuis n’importe où à Dubaï.',ar:'نعم، من أي مكان في دبي.',ph:'YÈS, from È-ni-ouèr inn dou-BAÏ'},
      {me:true,choices:['And can I cancel for free?','And can I cancel the lease?','And can I cancel my Emirates ID?'],fr:'Et puis-je annuler gratuitement ?',ar:'وهل يمكنني الإلغاء مجانًا؟',ph:'annd kann aï KANN-seul for FRI'},
      {who:'Agent',en:'Yes, until Friday noon.',fr:'Oui, jusqu’à vendredi midi.',ar:'نعم، حتى ظهر يوم الجمعة.',ph:'YÈS, ann-TIL FRAÏ-déï NOUN'},
      {scene:'3 · Déplacer un rendez-vous'},
      {who:'Receptionist',en:'Smile Dental Clinic, good morning.',fr:'Cabinet dentaire Smile, bonjour.',ar:'عيادة سمايل لطب الأسنان، صباح الخير.',ph:'SMAÏL DÈN-teul KLI-nik, goud MOR-ninng'},
      {me:true,choices:['Hello, I’d like to reschedule my appointment on Saturday.','Hello, I’d like to reschedule the safari.','Hello, I’d like to reschedule the rice.'],fr:'Bonjour, je voudrais déplacer mon rendez-vous de samedi.',ar:'مرحبًا، أريد تغيير موعدي يوم السبت.',ph:'hè-LO, aïd LAÏK tou ri-CHÈ-djoul maï eu-POÏNT-meunt onn SA-teur-déï'},
      {who:'Receptionist',en:'Of course. Are you available on Monday at five?',fr:'Bien sûr. Êtes-vous disponible lundi à dix-sept heures ?',ar:'بالتأكيد. هل أنت متاح يوم الاثنين الساعة الخامسة؟',ph:'ov KORS. ar you eu-VÉÏ-leu-beul onn MANN-déï at FAÏV'},
      {me:true,choices:['Yes, Monday at five is perfect. Thank you.','Yes, Monday at five is a virus.','Yes, Monday at five is furnished.'],fr:'Oui, lundi à dix-sept heures, c’est parfait. Merci.',ar:'نعم، الاثنين الساعة الخامسة مناسب تمامًا. شكرًا.',ph:'YÈS, MANN-déï at FAÏV iz PEUR-fikt. þANK you'}
    ]}
];
